name: Test github actions

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [13.x]

    steps:
      - uses: actions/checkout@v1
      - name: Build Code
        with:
          node-version: ${{ matrix.node-version }}
        run: |
          make lint


